@startuml diagrama

' Punto 2
entity alquiler {
    idAlquiler: Int PK
    --
    anuncio: Anuncio FK
    inquilino: inquilino FK
    duracion: Duracion FK
    fechaInicio: DateTime
    fechaFin: DateTime
    detalleImporte: DetalleImporte FK
    deposito: Float
    comision: Float
    gastosAveriguaciones: Float
    estadoAlquiler: Estado FK
    pagoAlquiler: PagoAlquiler FK
}


entity duracion {
    idDuracion: Int PK
    nombre: tipoPeriodo FK
    cantidad: Int
}

entity detalleImporte {
    idDetalleImporte: Int
    nroPeriodoInicio: Int
    nroPeriodoFin: Int
    precio: Int
}

entity pagoAlquiler {
    idPagoAlquiler: Int
    alquiler: Alquiler FK
    fechaPago: DateTime
    nroPeriodoPago: Int
    descripcionPeriodo: Varchar(255)
    fechaInicioPeriodo: DateTime
    fechaFinPeriodo: DateTime
    importe: Integer
    medioPago: MedioPago FK
}



entity medioPago {
    idMedioPago: Int
    nombre: Varchar(255)
}

entity venta {
    idVenta: Int
    anuncio: Anuncio FK
    comprador: comprador FK
    fechaDeVenta: DateTime
    precioDeVenta: Int
    monedaDelPrecioDeVenta: tipoDeMoneda FK
    pago: pagoVenta FK
    comisionInmobiliaria: Int
}

entity pagoVenta {
    importe: detalleImporte FK
    monedaDelPago: tipoDeMoneda FK
    cotizacion: Float
    medioDePago: medioPago FK
}

entity sucursal {
    codigoSucursal: Int PK
    direccion: direccion FK
    nombre: varchar(50)
    telefono: varchar(50)
}

entity anuncio {
    nroAnuncio: Int PK
    fechaPublicacion: DateTime
    agenteInmobiliario: agenteInmobiliario FK
    tipoOperacion: TipoOperacion FK
    inmueble: Inmueble FK
    precioPublicado: Double 
    moneda: tipoDeMoneda FK
    tipoPeriodo: TipoPeriodo FK
    estadoAnuncio: EstadoAnuncio FK
    fechaFinalizacion: DateTime
    costoPublicacion: Double
}

entity tipoDeMoneda {
    idMoneda: Int PK
    nombre: varchar(255)
}

/' PUNTO 1 '/
entity inmueble {
    nroInmueble: Int PK
    tipoDeInmueble: TipoDeInmueble FK  
    descripcion: Text
    propietario: propietario FK
    direccion: Direccion FK
    ambientes: Smallint
    superficieTotal: Int
    disposicion: Disposicion FK
    orientacion: orientacion FK
    estado: estado FK
    Antiguedad: Int
    expensas: Int
}

entity tipoDeInmueble {
    idTipoDeInmueble: Int PK
    nombre: varchar(255)
}


entity direccion {
    idDireccion: Int PK
    --
    barrio: Barrio FK 
    localidad: Localidad FK
    provincia: Provincia FK
    calle: Varchar(255)
    altura: Int
}

entity barrio {
    idBarrio: Int PK
    nombre: Varchar(255)
    localidad: Localidad FK

}

entity localidad {
    idLocalidad: Int
    nombre: Varchar(255)
    provincia: Provincia FK
}

entity provincia {
    idProvincia: Int
    nombre: Varchar(255)
}

provincia ||-|{ localidad
localidad ||-|{ barrio

direccion |o--|| barrio
direccion |o--|| localidad
direccion |o--|| provincia

entity tipoOperacion {
    idTipoOperacion: Int PK
    nombre: varchar(255)
}

entity agenteInmobiliario {
    idagente Int PK
    sucursal_id: Sucursal FK    
    nombre: Varchar(255)
    apellido: Varchar(255)
    dni: Varchar(30)
    mail: Varchar(255)

}


entity caracteristica {
    idCaracteristica PK
    nombre Varchar(255)
}


entity tipoPeriodo {
    idTipoPeriodo Int PK
    nombre: Varchar(255)
}

entity estadoAnuncio {
    idEstado Int PK
    nombre: varchar(255) 
}



entity disposicion {
    idDisposicion PK
    --
    nombre varchar(64)
}

entity orientacion {
    idOrientacion PK 
    nombre Varchar(255)
}

entity inmuebleCaracteristica {
    inmueble: Inmueble FK PK
    caracteristica: Caracteristica FK PK
}

entity estado {
    idEstado PK
    nombre Varchar(255)
}

entity estadoAlquiler {
    idEstadoAlquiler PK
    --
    nombre: Varchar(255)
}

entity persona {
    idpersona PK
    nombre: Varchar(255)
    apellido: Varchar(255)
    dni: Varchar(30)
    telefono: Varchar(30) 
    mail: Varchar(255)
    fechaRegistro: Date
    fechaNacimiento: Date
}

entity comprador{
    idcomprador PK
    --
    persona: persona FK
}

entity inquilino{
    idinquilino PK
    --
    persona: persona FK
}


entity propietario{
    idpropietario PK
    --
    persona: persona FK
}

entity agente {
    idagente PK
    --
    persona: persona FK
}






' Anuncio
agenteInmobiliario }|--||anuncio
anuncio }o--||  tipoOperacion 
anuncio }o--|| inmueble
tipoDeMoneda ||--o{ anuncio 
tipoPeriodo ||--o{ anuncio  
estadoAnuncio ||--o{ anuncio

' Inmbueble
inmueble }|--|| propietario
inmueble ||--o| direccion
inmueble }|--o| disposicion
inmueble }|--o| orientacion
estado ||--o{ inmueble
inmueble }o-|| tipoDeInmueble
inmuebleCaracteristica }|--o| inmueble
caracteristica |o--|{ inmuebleCaracteristica

propietario }o--|| direccion

' Alquiler
detalleImporte }|--||alquiler 
alquiler ||-|{ pagoAlquiler
estadoAlquiler }|--|| alquiler
alquiler ||--|| anuncio
alquiler ||--|{ duracion

duracion }|--|| tipoPeriodo


' Pagos
pagoAlquiler }o-|| medioPago
' medioPago ||--o{ pagoAlquiler

' Venta
venta ||--|| anuncio
venta }|--|| tipoDeMoneda
venta ||--|{ pagoVenta
pagoVenta ||--||detalleImporte
pagoVenta }o-|| medioPago

pagoVenta }o----|| tipoDeMoneda

alquiler ||--|{ inquilino
comprador ||--|{ venta
agente ||--|{ anuncio


' personas
propietario }|--|| persona
agente }|--|| persona
inquilino }|--|| persona
comprador }|--|| persona

 agente ||--|{ sucursal

@enduml
                                        























