DROP TABLE ANDY_Y_SUS_SEMINARAS.PagoAlquiler;
DROP TABLE ANDY_Y_SUS_SEMINARAS.PagoVenta;
DROP TABLE ANDY_Y_SUS_SEMINARAS.MedioPago;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Alquiler;
DROP TABLE ANDY_Y_SUS_SEMINARAS.EstadoAlquiler;
DROP TABLE ANDY_Y_SUS_SEMINARAS.DetalleImporte;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Duracion;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Anuncio;
DROP TABLE ANDY_Y_SUS_SEMINARAS.EstadoAnuncio;
DROP TABLE ANDY_Y_SUS_SEMINARAS.TipoPeriodo;
DROP TABLE ANDY_Y_SUS_SEMINARAS.TipoDeMoneda;
DROP TABLE ANDY_Y_SUS_SEMINARAS.TipoOperacion;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Comprador;


DROP TABLE ANDY_Y_SUS_SEMINARAS.Inquilino;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Agente;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Propietario;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Persona;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Estado;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Orientacion;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Disposicion;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Caracteristica;
DROP TABLE ANDY_Y_SUS_SEMINARAS.CantAmbientes;
DROP TABLE ANDY_Y_SUS_SEMINARAS.InmuebleCaracteristica;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Inmueble;
DROP TABLE ANDY_Y_SUS_SEMINARAS.PropietarioDeInmueble;
DROP TABLE ANDY_Y_SUS_SEMINARAS.TipoDeInmueble;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Direccion;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Barrio;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Localidad;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Provincia;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Venta;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Sucursal;


DROP PROCEDURE migrar_tipificado;
DROP PROCEDURE migrar_tipificados;
DROP PROCEDURE migrar_carateristica;
DROP PROCEDURE migrar_inquilinos;
DROP PROCEDURE migrar_agentes;
DROP PROCEDURE migrar_propietarios;
DROP PROCEDURE migrar_compradores;
DROP PROCEDURE migrar_provincias;
DROP PROCEDURE migrar_localidad;
DROP PROCEDURE migrar_barrios;
DROP PROCEDURE migrar_direccion;
DROP PROCEDURE migrar_inmueble;
DROP PROCEDURE migrar_sucursal;
DROP PROCEDURE migrar_anuncio;
DROP PROCEDURE migrar_propietario_inmueble;
DROP PROCEDURE migrar_tipo_periodo;
DROP PROCEDURE migrar_duracion;
DROP PROCEDURE migrar_pago_venta;
DROP PROCEDURE migrar_detalle_importe;
DROP PROCEDURE migrar_alquiler;
DROP PROCEDURE migrar_pago_alquiler;
DROP PROCEDURE migrar_venta;

DROP SCHEMA ANDY_Y_SUS_SEMINARAS;



