use GD2C2023
go

DROP TABLE ANDY_Y_SUS_SEMINARAS.PagoAlquiler;
DROP TABLE ANDY_Y_SUS_SEMINARAS.PagoVenta;
DROP TABLE ANDY_Y_SUS_SEMINARAS.MedioPago;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Alquiler;
DROP TABLE ANDY_Y_SUS_SEMINARAS.EstadoAlquiler;
DROP TABLE ANDY_Y_SUS_SEMINARAS.DetalleImporte;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Duracion;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Anuncio;
DROP TABLE ANDY_Y_SUS_SEMINARAS.EstadoAnuncio;
DROP TABLE ANDY_Y_SUS_SEMINARAS.TipoPeriodo;
DROP TABLE ANDY_Y_SUS_SEMINARAS.TipoDeMoneda;
DROP TABLE ANDY_Y_SUS_SEMINARAS.TipoOperacion;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Comprador;


DROP TABLE ANDY_Y_SUS_SEMINARAS.Inquilino;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Agente;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Propietario;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Persona;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Estado;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Orientacion;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Disposicion;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Caracteristica;
DROP TABLE ANDY_Y_SUS_SEMINARAS.CantAmbientes;
DROP TABLE ANDY_Y_SUS_SEMINARAS.InmuebleCaracteristica;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Inmueble;
DROP TABLE ANDY_Y_SUS_SEMINARAS.PropietarioDeInmueble;
DROP TABLE ANDY_Y_SUS_SEMINARAS.TipoDeInmueble;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Direccion;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Barrio;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Localidad;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Provincia;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Venta;
DROP TABLE ANDY_Y_SUS_SEMINARAS.Sucursal;


DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_tipificado;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_tipificados;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_carateristicas;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_caracteristica_inmueble;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_inquilinos;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_agentes;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_propietarios;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_compradores;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_provincias;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_localidad;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_barrios;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_direccion;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_inmueble;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_sucursal;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_anuncio;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_propietario_inmueble;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_tipo_periodo;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_duracion;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_pago_venta;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_detalle_importe;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_alquiler;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_pago_alquiler;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.migrar_venta;

DROP SCHEMA ANDY_Y_SUS_SEMINARAS;



