@startuml BI_Model

' Dimensiones
entity BI_DimTiempo {
    idTiempo: numeric PK
    --
    anio: numeric
    cuatrimestre: numeric
    mes: numeric
}

entity BI_DimUbicacion {
    idUbicacion: numeric PK
    --
    provincia: Provincia FK
    localidad: Localidad FK
    barrio: Barrio FK
}

entity BI_DimSucursal {
    idSucursal: numeric PK
    --
    nombre: nvarchar(100)
}

entity BI_DimRangoEtario {
    idRangoEtario: numeric PK
    --
    rango_inicio: numeric
    rango_fin: numeric
}

entity BI_DimTipoInmueble {
    idTipoInmueble: numeric PK
    --
    nombre: nvarchar(100)
}

entity BI_DimAmbientes {
    idAmbientes: numeric PK
    --
    ambientes: numeric
}

entity BI_DimRangoM2 {
    idRangoM2: numeric PK
    --
    rango_inicio: numeric
    rango_fin: numeric

}

entity BI_DimTipoOperacion {
    idTipoOperacion: numeric PK
    --
    nombre: nvarchar(100)
}

entity BI_DimTipoMoneda {
    idTipoMoneda: numeric PK
    --
    nombre: nvarchar(100)
}

' Hechos
entity BI_HechoAnuncio {
    idHechoAnuncio: numeric PK
    --
    tiempo: DimTiempo FK
    ubicacion: DimUbicacion FK
    sucursal: DimSucursal FK
    rangoEtarioAgentes: DimRangoEtario FK
    tipoInmueble: DimTipoInmueble FK
    ambientes: DimAmbientes FK
    rangoM2: DimRangoM2 FK
    tipoOperacion: DimTipoOperacion FK
    tipoMoneda: DimTipoMoneda FK
    promedioTiempoPublicado: numeric
    precioPromedio: numeric
    cantAnuncios: numeric
    cantOperacionesConcretadas: numeric
    montoTotalOperacionesConcretadas: numeric
    

}

entity BI_HechoAlquiler {
    idHechoAlquiler: numeric PK
    --
    tiempo: DimTiempo FK
    ubicacion: DimUbicacion FK
    sucursal: DimSucursal FK
    rangoEtarioInquilinos: DimRangoEtario FK
    rangoEtarioAgentes: DimRangoEtario FK
    tipoInmueble: DimTipoInmueble FK
    ambientes: DimAmbientes FK
    rangoM2: DimRangoM2 FK
    tipoMoneda: DimTipoMoneda FK
    cantAlquileres: numeric
    porcentajeIncumplimientoPagos: numeric
    promedioComision: numeric
    


}

entity BI_HechoVenta {
    idHechoVenta: numeric PK
    --
    tiempo: DimTiempo FK
    ubicacion: DimUbicacion FK
    sucursal: DimSucursal FK
    rangoEtarioAgentes: DimRangoEtario FK
    rangoEtarioAgentes: DimRangoEtario FK
    tipoInmueble: DimTipoInmueble FK
    ambientes: DimAmbientes FK
    rangoM2: DimRangoM2 FK
    tipoMoneda: DimTipoMoneda FK
    cantVentas: numeric
    precioPromedioPorM2: numeric
    promedioComision: numeric
    
    

}

BI_DimTiempo }o--|| BI_HechoAnuncio
BI_DimTiempo }o--|| BI_HechoAlquiler
BI_DimTiempo }o--|| BI_HechoVenta

BI_DimUbicacion }o--|| BI_HechoAnuncio
BI_DimUbicacion }o--|| BI_HechoAlquiler
BI_DimUbicacion }o--|| BI_HechoVenta

BI_DimSucursal }o--|| BI_HechoAnuncio
BI_DimSucursal }o--|| BI_HechoAlquiler
BI_DimSucursal }o--|| BI_HechoVenta

BI_DimRangoEtario }o--|| BI_HechoAnuncio
BI_DimRangoEtario }o--|| BI_HechoAlquiler
BI_DimRangoEtario }o--|| BI_HechoVenta

BI_DimTipoInmueble }o--|| BI_HechoAnuncio
BI_DimTipoInmueble }o--|| BI_HechoAlquiler
BI_DimTipoInmueble }o--|| BI_HechoVenta

BI_DimAmbientes }o--|| BI_HechoAnuncio
BI_DimAmbientes }o--|| BI_HechoAlquiler
BI_DimAmbientes }o--|| BI_HechoVenta

BI_DimRangoM2 }o--|| BI_HechoAnuncio
BI_DimRangoM2 }o--|| BI_HechoAlquiler
BI_DimRangoM2 }o--|| BI_HechoVenta

BI_DimTipoOperacion }o--|| BI_HechoAnuncio

BI_DimTipoMoneda }o--|| BI_HechoAnuncio
BI_DimTipoMoneda }o--|| BI_HechoAlquiler
BI_DimTipoMoneda }o--|| BI_HechoVenta

@enduml
