-- Drop de las tablas
DROP TABLE ANDY_Y_SUS_SEMINARAS.BI_dim_tiempo;
DROP TABLE ANDY_Y_SUS_SEMINARAS.BI_dim_ubicacion;
DROP TABLE ANDY_Y_SUS_SEMINARAS.BI_dim_sucursal;
DROP TABLE ANDY_Y_SUS_SEMINARAS.BI_dim_rango_etario;
DROP TABLE ANDY_Y_SUS_SEMINARAS.BI_dim_tipo_inmueble;
DROP TABLE ANDY_Y_SUS_SEMINARAS.BI_dim_ambientes;
DROP TABLE ANDY_Y_SUS_SEMINARAS.BI_dim_rango_m2;
DROP TABLE ANDY_Y_SUS_SEMINARAS.BI_dim_tipo_operacion;
DROP TABLE ANDY_Y_SUS_SEMINARAS.BI_dim_tipo_moneda;
DROP TABLE ANDY_Y_SUS_SEMINARAS.BI_hecho_anuncio;
DROP TABLE ANDY_Y_SUS_SEMINARAS.BI_hecho_alquiler;
DROP TABLE ANDY_Y_SUS_SEMINARAS.BI_hecho_venta;

-- Drop de las funciones
DROP FUNCTION ANDY_Y_SUS_SEMINARAS.CUATRIMESTRE;
DROP FUNCTION ANDY_Y_SUS_SEMINARAS.ObtenerRangoEtarioID;
DROP FUNCTION ANDY_Y_SUS_SEMINARAS.ObtenerRangoM2ID;

-- Drop de los procedimientos
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.BI_MigracionSucursal;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.BI_MigracionTiempo;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.BI_MigracionRangoEtario;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.MigracionRangoMetrosCuadrados;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.BI_MigracionTipoMoneda;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.BI_MigracionTipoOperacion;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.BI_MigracionTipoInmueble;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.BI_MigracionAmbientes;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.BI_MigracionUbicacion;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.BI_MigracionHechoAnuncio;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.BI_MigracionHechoAlquiler;
DROP PROCEDURE ANDY_Y_SUS_SEMINARAS.BI_MigracionHechoVenta;

-- Drop de las vistas
DROP VIEW ANDY_Y_SUS_SEMINARAS.VistaDuracionPromedioAnuncios;
DROP VIEW ANDY_Y_SUS_SEMINARAS.VistaPrecioPromedioAnuncios;
-- Continuar con el resto de las vistas, si las hubiera

